repos:
  - repo: local
    hooks:
      - id: dart-format
        name: Dart Format
        entry: dart format --set-exit-if-changed .
        language: system
        files: \.dart$
        pass_filenames: false
        
      - id: flutter-analyze
        name: Flutter Analyze
        entry: flutter analyze
        language: system
        files: \.dart$
        pass_filenames: false
        
      - id: flutter-test
        name: Flutter Test
        entry: flutter test
        language: system
        files: \.dart$
        pass_filenames: false
